before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libeXosip2

language: python
python:
  - "2.7"
  - "3.5"
# command to install dependencies
install:
  - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then pip install --user -r requirements-lt_3.2.txt; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3.5 ]]; then pip install --user -r requirements.txt; fi
# command to run tests
script:
  - cd src
  - python -m unittest
