install:
  - wget http://ftp.gnu.org/gnu/osip/libosip2-5.0.0.tar.gz
  - tar -xzvf libosip2-5.0.0.tar.gz
  - cd libosip2-5.0.0
  - ./configure
  - make
  - sudo make install
  - cd ../
  - wget http://download.savannah.gnu.org/releases/exosip/libexosip2-5.0.0.tar.gz
  - tar -xzvf libexosip2-5.0.0.tar.gz
  - cd libexosip2-5.0.0
  - ./configure
  - make
  - sudo make install
  - cd ../
  - sudo ldconfig
  - if [[ $TRAVIS_PYTHON_VERSION < '3.2' ]]; then pip install mock; fi
  - pip install coverage codacy-coverage

language: python
python:
  - "2.7"
  - "3.5"

# command to run tests
script:
  - python setup.py install
  - mv src/exosip2ctypes/tests ./
  - coverage run -m unittest discover

after_success:
  - coverage xml
  - python-codacy-coverage -r coverage.xml
