install:
  - wget http://ftp.gnu.org/gnu/osip/libosip2-5.0.0.tar.gz
  - tar -xzvf libosip2-5.0.0.tar.gz
  - cd libosip2-5.0.0
  - ./configure
  - make
  - sudo make install
  - cd ../
  - wget http://download.savannah.gnu.org/releases/exosip/libexosip2-5.0.0.tar.gz
  - tar -xzvf libexosip2-5.0.0.tar.gz
  - cd libexosip2-5.0.0
  - ./configure
  - make
  - sudo make install
  - cd ../
  - sudo ldconfig
  - if [[ $TRAVIS_PYTHON_VERSION < '3.3' ]]; then pip install --upgrade mock; fi
  - pip install --upgrade coverage codacy-coverage
  - python setup.py install

language: python
python:
  - "2.7"
  - "3.5"

# command to run tests
script:
  - mv src/exosip2ctypes/tests ./
  - coverage run -m unittest discover
  - mv tests src/exosip2ctypes

after_success:
  - coverage xml
  - python-codacy-coverage -r coverage.xml

deploy:
  provider: pypi
  user: PYPI_USER
  password: PYPI_PASSWORD
  on:
    tags: true
