"""
:date: 2016-02-03
:author: liuxy
"""
#: see `osip/include/osipparser2/osip_port.h`

OSIP_SUCCESS = 0
OSIP_UNDEFINED_ERROR = -1
OSIP_BADPARAMETER = -2
OSIP_WRONG_STATE = -3
OSIP_NOMEM = -4
OSIP_SYNTAXERROR = -5
OSIP_NOTFOUND = -6
OSIP_API_NOT_INITIALIZED = -7
OSIP_NO_NETWORK = -10
OSIP_PORT_BUSY = -11
OSIP_UNKNOWN_HOST = -12
OSIP_DISK_FULL = -30
OSIP_NO_RIGHTS = -31
OSIP_FILE_NOT_EXIST = -32
OSIP_TIMEOUT = -50
OSIP_TOOMUCHCALL = -51
OSIP_WRONG_FORMAT = -52
OSIP_NOCOMMONCODEC = -53
